prevents an empty/null byte filename
if the page containing the filename has been paged out, filename contains just a null byte which leads to certain side effects
e.g. 
- a vad that appears to be a mapped section backed by the page file, instead of a loaded image/data file
- an exception while trying to dump/disassemble content for that file (see example stack trace output below)

    disassembler.render(renderer, suppress_headers=True)
  File "/rekall/lib/python3.7/site-packages/rekall_core-1.7.2rc1-py3.7.egg/rekall/plugins/tools/disassembler.py", line 447, in render
    return super(Disassemble, self).render(renderer, **options)
  File "/rekall/lib/python3.7/site-packages/rekall_core-1.7.2rc1-py3.7.egg/rekall/plugin.py", line 761, in render
    for row in self.collect():
  File "/rekall/lib/python3.7/site-packages/rekall_core-1.7.2rc1-py3.7.egg/rekall/plugins/tools/disassembler.py", line 460, in collect
    offset)
  File "/rekall/lib/python3.7/site-packages/rekall_core-1.7.2rc1-py3.7.egg/rekall/plugins/common/address_resolver.py", line 335, in get_nearest_constant_by_address
    if module.profile != None:
  File "/rekall/lib/python3.7/site-packages/rekall_lib/utils.py", line 1091, in __get__
    return super(safe_property, self).__get__(*args, **kwargs)
  File "/rekall/lib/python3.7/site-packages/rekall_core-1.7.2rc1-py3.7.egg/rekall/plugins/windows/address_resolver.py", line 182, in profile
    return self.load_profile(force=False)
  File "/rekall/lib/python3.7/site-packages/rekall_core-1.7.2rc1-py3.7.egg/rekall/plugins/windows/address_resolver.py", line 188, in load_profile
    self.session.LoadProfile(profile_name) or
  File "/rekall/lib/python3.7/site-packages/rekall_core-1.7.2rc1-py3.7.egg/rekall/session.py", line 968, in LoadProfile
    session=self)
  File "/rekall/lib/python3.7/site-packages/rekall_lib/registry.py", line 96, in __call__
    res = super(UniqueObjectIdMetaclass, cls).__call__(*args, **kwargs)
  File "/rekall/lib/python3.7/site-packages/rekall_core-1.7.2rc1-py3.7.egg/rekall/io_manager.py", line 344, in __init__
    self.check_dump_dir(self.dump_dir)
  File "/rekall/lib/python3.7/site-packages/rekall_core-1.7.2rc1-py3.7.egg/rekall/io_manager.py", line 410, in check_dump_dir
    if not os.path.isdir(dump_dir):
  File "/rekall/lib/python3.7/genericpath.py", line 42, in isdir
    st = os.stat(s)
ValueError: embedded null byte